### PR TITLE
Harry's notes on Nested.lhs

### PR DESCRIPTION
**Pull request by hgoldstein95**

### CODE REVIEW

**Comment by sweirich** [comment]
Thanks Harry. I have revised the file based on your notes. I'd like to wrap this up. What do you think about moving forward with this as a blog post?

**Comment by hgoldstein95** [comment]
Sorry, last week was a lot. Let's try to get this published on Friday? I'll send it around to a few people for comments.

We'll need to markdown-ify this at some point. I bet there's an automated way to turn LHS into markdown, but we can't actually publish an LHS file on the site.

**Comment by sweirich** [comment]
Thanks. 

pandoc can certainly turn it into HTML if that works. Maybe also markdown, but I haven't tried.

**Comment by hgoldstein95** [comment]
HTML is a subset of markdown, so that would probably work with a bit of manipulation. I'll take a look later in the week.

**Comment by sweirich** [comment]
Cleaning up old PR

**Pull request closed without merging**
